### ISSUE TITLE
Question about folders

### ISSUE THREAD

**Issue by SushiFart** [findix/ArtStationDownloader#1]
Hello!
I really hope Im not bothering you, I just found your artstation downloader software and im loving it, I follow such a bunch of awesome people here and you made my life lot easier downloading their pictures, thanks!

I just have only one question to ask, is there a way to organize all the user's images in just one folder?  

Thanks in advance! keep on the good work!

**Comment by findix** [comment]
Different user may have the same image name, it's not unique.
If you just want let all the images lay in the same folder. Try inputing *.* in the search box of the file explorer. 
I'm happy if you can tell me more about why you need this feature.

**Comment by chichi233** [comment]
I really hope Im not bothering you ：） 
I am an art student, and the art website has helped me immensely. I need to see and copy other artists' works, so I need to collect many works of art. Thank you very much for your work. My request is the same as the above friends, if an artist's work can be in the same folder, then in the future after finishing the search, it can bring great help and improve efficiency.
You've solved my big business! I would like to express my sincere thanks to you.

**Comment by findix** [comment]
What do you think if I add a option let you can choice whether every works of each artist in the same folder or each project has it's own folder?

**Comment by findix** [comment]
https://github.com/findix/ArtStationDownloader/releases/tag/v0.3.0
It's done!
