### ISSUE TITLE
[Request] Download the whole content in one directory

### ISSUE THREAD

**Issue by scotrod** [findix/ArtStationDownloader#11]
Hi there, any chance of adding an option to download the whole content in just one directory instead of creating a folder for every single picture?

**Comment by LabmenNo001** [comment]
同求

**Comment by Kaidzuu** [comment]
Same request

**Comment by findix** [comment]
https://github.com/findix/ArtStationDownloader/releases/tag/v0.3.0
It's done!

**Comment by scotrod** [comment]
> https://github.com/findix/ArtStationDownloader/releases/tag/v0.3.0 It's done!

Thanks a lot!
