### ISSUE TITLE
Request: To download original image, instead of downscaled one.

### ISSUE THREAD

**Issue by GoHoo** [findix/ArtStationDownloader#12]
Artstation hides original images behind a paywall, so in order to show original (2k,4k etc.) image artists have to sub to arts sub-service.
So let me show you an example ;
Here is the original image link 
// **assets/images/images/023/856/215/4k/shuo-shi-14-2.jpg?1580559957**

AND

Here is downscaled one, the one that which will be downloaded
// **assets/images/images/023/856/215/large/shuo-shi-14-2.jpg?1580559957**

As you can see it just one word in the link, Im not sure if it's possible or not but it would be great if your app could download 4k one.

**Comment by findix** [comment]
Thank you for your advice. This feature is release now.
https://github.com/findix/ArtStationDownloader/releases/tag/v0.2.1
