### ISSUE TITLE
同名图片覆盖问题

### ISSUE THREAD

**Issue by peekapop** [findix/ArtStationDownloader#2]
findix大大,
        感谢您开发的工具, 使用起来非常方便
        测试的时候,遇到了点问题.  发现抓取了图片之后会按**图片本身名字**储存到各自文件夹中,但**同一个文件夹下如果有重名文件, 原先的图片就会被覆盖掉**,就比如[这两张图](https://www.artstation.com/artwork/KJKxR) ( 因这两张图片本身是重名的,所以实际上存取下来的只有一张 ) , 请教下后面是否会考虑加判断重名或者重新命名的功能呢? ( 第一次提交issue,不知道有没有讲清楚,很惭愧自己不懂Python帮不上忙 = =||| )
        再次感谢你和你的工作成果

**Comment by findix** [comment]
感谢你发现问题，这个问题的解决方案可能只有给每张图片名称的前面或后面加上一串独立的数字id了，这样可能导致看起来不方便，不过对比一下，感觉还是少掉一张图比较严重。这个我抽时间会解决一下。

**Comment by cuihaifu** [comment]
哇开心这个下载插件的作者是个中国人，希望作者大大能修复被403的问题。

**Comment by cuihaifu** [comment]
另外

> findix大大,
> 感谢您开发的工具, 使用起来非常方便
> 测试的时候,遇到了点问题. 发现抓取了图片之后会按**图片本身名字**储存到各自文件夹中,但**同一个文件夹下如果有重名文件, 原先的图片就会被覆盖掉**,就比如[这两张图](https://www.artstation.com/artwork/KJKxR) ( 因这两张图片本身是重名的,所以实际上存取下来的只有一张 ) , 请教下后面是否会考虑加判断重名或者重新命名的功能呢? ( 第一次提交issue,不知道有没有讲清楚,很惭愧自己不懂Python帮不上忙 = =||| )
> 再次感谢你和你的工作成果

其实我当时发现了这个问题，我后来写了个重命名以及删除文件夹的python，然后让python识别下如果两张图一模一样，就保留旧的，新的删除，但现在也下载不了了

**Comment by findix** [comment]
@cuihaifu 这个问题确实很令人头大（
