### ISSUE TITLE
如何在国内访问到artstation网站的

### ISSUE THREAD

**Issue by DimendionalPlane** [findix/ArtStationDownloader#22]
请问，您是如何处理，使得在国内可以访问到artstation网站的。
我之前有尝试开启v2nray后，使用python的requests库来进行访问，但是仍然无法访问，而使用您的工具就可以获取到图片。

**Comment by DimendionalPlane** [comment]
I find the reason. I should make requests.session() to keep connected.

**Comment by findix** [comment]
是提示了`web request error` 吗？ 那确实是这个问题。
话说，如果有兴趣改进这个App的话，非常欢迎你成为贡献者~
