### ISSUE TITLE
Fix: bug coming from the comment like system

### ISSUE THREAD

**Issue by David-Moisan** [findix/ArtStationDownloader#23]
When I click on the number of likes (on a comment) I noticed that the counter panics, indeed I managed to like 3 times / times the same comment and go down. See video below.

https://user-images.githubusercontent.com/62502246/158208768-2012f4f5-7126-4a7b-91b1-5ab623dc0da1.mp4

**Comment by findix** [comment]
Hi David,
This project is not ArtStation itself. It's just a tool.
Maybe you can try to contact the ArtStation by sending an e-mail ([support@artstation.com](mailto:support@artstation.com))

**Comment by David-Moisan** [comment]
Hi findix sorry 😂
