### ISSUE TITLE
i got this error what i do?

### ISSUE THREAD

**Issue by Alethy** [findix/ArtStationDownloader#24]
[Error] [403 Forbidden] You are blocked by artstation

**Comment by pxlovenn** [comment]
Yes, I have this problem, too。

“[Error] [403 Forbidden] You are blocked by artstation
========ALL DONE========”

wish could fix this problem。

**Comment by findix** [comment]
https://github.com/findix/ArtStationDownloader#faq

## FAQ

> **Why I get a message says `[Error] [403 Forbidden] You are blocked by artstation`?**

The ArtStation has a [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA) system (by Cloudflare) which need you proof you are human otherwise forbid you. I haven't found a way solve this for now. If you have idea, please tell me.

**Comment by Gitphex** [comment]
[Error] [403 Forbidden] You are blocked by artstation

Yes, i used the program without problems until today, i hope you can fix it **findix**, but still thanks a lot for doing this app.

Greetings.

**Comment by samarthshrivas** [comment]
> https://github.com/findix/ArtStationDownloader#faq
> ## FAQ
> 
> > **Why I get a message says `[Error] [403 Forbidden] You are blocked by artstation`?**
> 
> The ArtStation has a [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA) system (by Cloudflare) which need you proof you are human otherwise forbid you. I haven't found a way solve this for now. If you have idea, please tell me.


NOT A PERMANENT SOLUTION😢
https://pypi.org/project/cloudscraper/

Use cloudscraper to bypass Cloudflare

```

import cloudscraper
import time
def rget(url):
    for i in range(20):
        scraper = cloudscraper.create_scraper()
        g = scraper.get(url)
        if g.status_code == 200 :
            return g
            break
        else:
            print(f"trying again {g}", end = "\r")
            
            time.sleep(2)
    print("stucked on cloudflare protection tried 20 times")
r = https://www.artstation.com/users/nixri/projects.json
print(r.json())


```
Try this it worked for me.

**Comment by findix** [comment]
Oh thank you @samarthshrivas ! I will try then!

**Comment by findix** [comment]
Oh thank you @samarthshrivas ! I will try then!

**Comment by samarthshrivas** [comment]
> Oh thank you @samarthshrivas ! I will try then!

Got a permanent solution check my  repo 😎 reused a lot of code from your core.py
https://github.com/samarthshrivas/ArtStationDownloader/

use this https://{username}.artstation.com/rss 
return xml file of projects

**Comment by findix** [comment]
I tried your solution and it seems solved. awesome !

**Comment by findix** [comment]
@Alethy @pxlovenn @Gitphex
It's fixed. try https://github.com/findix/ArtStationDownloader/releases/tag/v0.2.1

**Comment by Alethy** [comment]
It worked!! thank you so much <3

**Comment by pxlovenn** [comment]
Sorry ~ I'm stupid and still haven't solved it...
I added my proxy address to the “config.ini” file
I don't know if it's my proxy setting problem~
![1](https://user-images.githubusercontent.com/104475724/168219633-10f53f15-9ebb-4a88-8a68-0d2fb1d49ef6.png)
![2](https://user-images.githubusercontent.com/104475724/168219656-67db14be-8dba-48e5-a3ff-801966229412.png)
PS：In fact, I've tried every one, but it's useless.

There are no results after clicking ↓
![image](https://user-images.githubusercontent.com/104475724/168220064-3acb659b-a997-42dd-a4bc-5aeadbb100bd.png)

**Comment by findix** [comment]
@pxlovenn 

> 我看你界面是中文，并且这个问题应该只会在国内遇到，所以就用中文回复了。

你确认配置正确吗？不需要设置系统代理，但是需要确认端口正确，看你用的好像是SSR？默认端口可能是1080，麻烦你可以确认一下，另外也需要确认软件支持的代理类型，是否支持http代理。

**Comment by pxlovenn** [comment]
嗨~看到中文 倍感亲切！我之前0.11版的时候可以用  代理设置没有变动。
你指的“需要确认软件支持的代理类型，是否支持http代理”  我该怎么确认？  
不知道你方不方便  能否加个Q（429235586） 指导下 
![40B51B0IS${ZX AE B(EHRY](https://user-images.githubusercontent.com/104475724/168269815-1ebb8d64-ab6d-411c-8e3d-40605d40841a.png)

**Comment by pxlovenn** [comment]
今天用 神奇的可以了！！谢谢大神~ 你这个软件 我非常喜欢~
![33ZP(L0_BU5T9%IEMWO_`OE](https://user-images.githubusercontent.com/104475724/168407478-461d6b95-fec9-473a-bf04-598ee4cc40cd.png)

**Comment by malochen** [comment]
太棒了，感谢大佬的软件！爱你

**Comment by lzyamos99032** [comment]
Hey, love your app so much, but today I tried using this app again  "[Error] [403 Forbidden] You are blocked by artstation"
popped out again, IDK if artstation change something or what, and I've tried the solution https://github.com/findix/ArtStationDownloader/issues/24?new_signup=true?new_signup=true#issuecomment-1124734529
Unlucky, not working.  Hope we can have a new updated version, thanks!! 

App version: 0.3.3
Last used date: 30-Mar-24
