### ISSUE TITLE
点击下载按钮之后没有反应怎么解决？

### ISSUE THREAD

**Issue by JKbasara** [findix/ArtStationDownloader#25]
之前的artstaion downloader 版本，我在只用自己的v2rayN的时候，可以正常下载。
自从A站使用了反爬机制之后，我用作者您的新版下载器，打开代理的情况下点击下载download按钮会出现没有反应的情况。此时，download按钮变成灰色:
![image](https://user-images.githubusercontent.com/4019752/170425561-f1529adc-e6e4-4e15-8e5d-17d86b30e7bd.png)

同时，V2RN显示如下内容：
app/proxyman/inbound: connection ends > proxy/http: failed to read http request > read tcp 127.0.0.1:XXXXX->127.0.0.1:YYYYY: wsarecv: An existing connection was forcibly closed by the remote host （XXXXX和YYYYY是两个端口号。）

不知道怎么解决，麻烦作者您帮我看看。非常感谢~~~

**Comment by findix** [comment]
代理需要根据README里说明的，在config.ini中手动设置，你是开启了系统代理吗？Python 最近（两周内）刚刚修复了系统代理的问题，https://github.com/python/cpython/issues/86793 ，所以暂时得等更新，目前请确认手动设置了代理。没有响应的情况就是因为被墙了，所以http卡死没有返回结果。奇怪的是我尝试设置了timeout但是完全不生效有点迷惑……

**Comment by findix** [comment]
我确认了一下，目前如果开启了系统代理，是一定会失败的，暂时得等待 Python 修复这个问题。
建议更新一下最新的发布 https://github.com/findix/ArtStationDownloader/releases/tag/v0.2.2
然后关闭系统代理，再尝试一下，这个版本如果有问题是会报错的，你可以把错误信息提交上来。

**Comment by JKbasara** [comment]
> 我确认了一下，目前如果开启了系统代理，是一定会失败的，暂时得等待 Python 修复这个问题。 建议更新一下最新的发布 https://github.com/findix/ArtStationDownloader/releases/tag/v0.2.2 然后关闭系统代理，再尝试一下，这个版本如果有问题是会报错的，你可以把错误信息提交上来。

我已经开启了系统的全局代理，同时也在config.ini 添加了对应的proxy的设置。之前在用旧版去下载的时候，没出现这个问题。看来应该是python的事情。太感谢您了，辛苦大佬~~~

0.2.2版本：
在设置后代理之后。下载时出现如下报错：
HTTPSConnectionPool(host='deadman.artstation.com', port=443): Max retries exceeded with url: /rss?page=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
python 版本：3.10.4

**Comment by findix** [comment]
关闭系统代理应该就可以了

**Comment by JKbasara** [comment]
> 关闭系统代理应该就可以了

谢谢作者您，下载成功了。

**Comment by findix** [comment]
https://github.com/python/cpython/pull/26307
https://docs.python.org/release/3.9.13/whatsnew/changelog.html
Python 3.9.13 已经修复了这个问题，代码不变，我重新发布了一个Release。
https://github.com/findix/ArtStationDownloader/releases/tag/v0.2.2
现在问题解决了
