### ISSUE TITLE
Seems that simply doesn't work anymore.

### ISSUE THREAD

**Issue by Gitphex** [findix/ArtStationDownloader#28]
Seems that simply doesn't work anymore.

After pasting the username and click in the Download button nothing happen. Used to work before, but last time i used was like a few weeks ago i think.
I hope you can fix it and thank you so much for the program.

Greetings.

**Comment by samarthshrivas** [comment]
Hello @Gitphex 
Does it give ` 403 You are blocked by artstation ` error code?

**Comment by etahamad** [comment]
> Hello @Gitphex Does it give `403 You are blocked by artstation` error code?

yes

**Comment by samarthshrivas** [comment]
@etahamad @Gitphex @findix created a PR #29 that might work

**Comment by Gitphex** [comment]
Yeah, i got "403 You are blocked by artstation".

**Comment by Gitphex** [comment]
Also, i just noticed that both the .zip file and the .exe file are not 0.3.0, is 0.2.2, where can i download the 0.3.0?

Thanks in advance. Greetings.

**Comment by Gitphex** [comment]
> @etahamad @Gitphex @findix created a PR #29 that might work

And where is the link, or there is no build yet?

**Comment by samarthshrivas** [comment]
@Gitphex check this my fork release https://github.com/samarthshrivas/ArtStationDownloader/releases/tag/artstation
findix seems offline

**Comment by samarthshrivas** [comment]
> @Gitphex check this my fork release https://github.com/samarthshrivas/ArtStationDownloader/releases/tag/artstation findix seems offline

@Gitphex also update me if it is working for you

**Comment by Gitphex** [comment]
> > @Gitphex check this my fork release https://github.com/samarthshrivas/ArtStationDownloader/releases/tag/artstation findix seems offline
> 
> @Gitphex also update me if it is working for you

Yes, i just tried and works perfect, thank you so much for the fast answer.

Greetings.

**Comment by findix** [comment]
sorry for missing too much. 
Thanks for your help @samarthshrivas 
I'll handle on this asap.
