### ISSUE TITLE
系统环境条件有哪些

### ISSUE THREAD

**Issue by wangzhenjjcn** [findix/ArtStationDownloader#3]
比如  system 要不要osx 或者win Ubuntu
还有python 是2.7还是3.7
是32位还是64位
希望加一下~
感谢

**Comment by findix** [comment]
项目完全是Python脚本，理论上是跨平台的，版本的话，是需要Python 3（需要对Python 2兼容的话改起来也不麻烦），32位还是64位都可以。
因为自己这边目前没有尝试过在除Windows以外的平台上打包，如果你有需要的话，可以自己尝试build，如果发现有什么问题也非常欢迎提Issue。
感谢你的建议，后面如果有更新的话，我会说明一下需要Python 3。
