### ISSUE TITLE
Not sure if it's me or the program but I keep getting this.

### ISSUE THREAD

**Issue by CyephireXD** [findix/ArtStationDownloader#32]
HTTPSConnectionPool(host='www.artstation.com', port=443): Max retries exceeded with url: /projects/LerXw.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000136A9B40590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

Don't understand the issue with the proxy I copy and paste the ones I got on here in the config.ini

Not sure how this site works so wasn't sure if I was supposed to do with the issue.

**Comment by findix** [comment]
Can you try the recently version?
https://github.com/findix/ArtStationDownloader/releases/tag/v0.3.2
or you can show me your config file please. I'll check it.

**Comment by CyephireXD** [comment]
So didn't understand the proxy stuff but my dad said we don't have any proxy system at home was at the time trying to make one without fully understanding its a device system which I don't have.

**Comment by findix** [comment]
OK, proxy is not necessary for everyone. I'll close this for now. If you have any other confusing. Please tell me.
