### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by macworld1410** [findix/ArtStationDownloader#35]
<img width="461" alt="Screenshot 2023-08-12 144411" src="https://github.com/findix/ArtStationDownloader/assets/142076642/3c15c5f0-c61f-459a-ab01-fd2b393c734c">

if the username had "_" underscore between their username, it give error like this, :)

thank you :D

**Comment by findix** [comment]
fixed in https://github.com/findix/ArtStationDownloader/releases/tag/v0.3.3
