### ISSUE TITLE
真是个悲伤的故事：最近几天软件无法下载啦[哭唧唧]

### ISSUE THREAD

**Issue by huissv** [findix/ArtStationDownloader#5]
例子：https://www.artstation.com/ryantien
图片：
![20190331204219](https://user-images.githubusercontent.com/48523271/55289230-33585d00-53f6-11e9-94d8-5fcee80bffd0.png)

**Comment by findix** [comment]
感谢反馈……难道是网站改了结构么……我看看

**Comment by findix** [comment]
![image](https://user-images.githubusercontent.com/3446387/55409537-c929ee80-5594-11e9-9af3-60c7c99cc0d3.png)
我试了一下完全没问题呀，你这边直接访问ArtStation是可以的吗？或者你可以尝试源码运行，看看有没有报错

**Comment by huissv** [comment]
感谢。应该是我这边的问题吧，不过我不怎么懂这方面的，有空我换个系统试下  ╮(๑•́ ₃•̀๑)╭
另外：推荐一个文件夹合并软件，与之搭配非常不错
Folder Merger v1.8 （件夹合并英文版）
官方免费版下载地址(单文件版)： https://2xdsoft.de.tl/Folder-Merger.htm
使用说明：
![20190403003610](https://user-images.githubusercontent.com/48523271/55421131-25980880-55ab-11e9-8a0c-0bd318e3b98c.png)

**Comment by huissv** [comment]
补充：A站似乎是被墙的了，才发现（虽然可以翻上。。） π__π

**Comment by udterry** [comment]
> 补充：A站似乎是被墙的了，才发现（虽然可以翻上。。） π__π

VPN用全局模式就能下载了

**Comment by findix** [comment]
墙的问题我就无解啦（哭笑
没有把所有图片放在统一目录主要还是因为文件名可能会相同，防止冲突，如果有需要确实也有很多软件可以方便的处理。
