### ISSUE TITLE
显示please input right usernames?

### ISSUE THREAD

**Issue by CortinthusYu** [findix/ArtStationDownloader#6]
![image](https://user-images.githubusercontent.com/35418849/56293903-9408c900-615c-11e9-9101-79cf3a5eb62f.png)
会不会是编码或者网络的问题？

**Comment by jakem72360** [comment]
I've narrowed the problem down to the script failing to retrieve the `projects.json` file for a given artist. This causes the misleading error message making the user believe they've entered an invalid username. The problem, is that the script is being given a 403 response and being asked to fill out a CAPTCHA. I believe this can be rectified if cookies are enabled within the HTTP Requests API.

**Comment by CortinthusYu** [comment]
> I've narrowed the problem down to the script failing to retrieve the `projects.json` file for a given artist. This causes the misleading error message making the user believe they've entered an invalid username. The problem, is that the script is being given a 403 response and being asked to fill out a CAPTCHA. I believe this can be rectified if cookies are enabled within the HTTP Requests API.

thank you very much for your advice!><

**Comment by Brianwindows102018** [comment]
hello, how do we fix this??

**Comment by findix** [comment]
Just like @jakem72360 says. It's caused by CAPTCHA of Cloudflare.
I add a notice and cookie support in the new version. but once you are blocked. I don't know how to unblock.
If someone have an idea, please tell me.

**Comment by findix** [comment]
It's fixed. try latest https://github.com/findix/ArtStationDownloader/releases
